baseURL = 'https://ironpot.netlify.app/'
title = 'Paper'
theme = 'paper'
copyright = "Copyright © 2021, ironpot; all rights reserved."
paginate = 5
languageCode = "ko"
DefaultContentLanguage = "ko"
enableInlineShortcodes = true

#disqus 주석할 경우, github uttrences 를 기본 댓글 기능으로 사용한다.
#disqusShortname = 'dev-ironpot'   # add disqus comments
#githubRepo
githubRepo = 'dev-ironpot/blog-comments'
<<<<<<< HEAD
#googleAnalytics = 'UA-213499305-1'
googleAnalytics = 'G-4Y1MXZV2EE'
=======
googleAnalytics = "UA-213499305-1"
>>>>>>> 6d622950840279dcb00849dd850912cb4173282f


[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  disableHLJS = true                         # don't use highlight.js
  twitter = 'devironpot'                # twitter.com/YOUR_TWITTER_ID
  github = 'dev-ironpot'                  # github.com/YOUR_GITHUB_ID
  instagram = 'dev.ironpot'            # instagram.com/YOUR_INSTAGRAM_ID
  description = '설명입니다.'

#[permalinks]
# posts = '/:year/:month/:title/'

[menu]
[[menu.main]]
  identifier = 'menu-about'
  name = 'about me'
  pre = "<i class='fas fa-heart'></i>"
  url = '/about'
  weight = -110
[[menu.main]]
  identifier = 'menu-projects'
  name = 'projects'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fas fa-camera'></i>"
  url = '/projects/'
  weight = -100
[[menu.main]]
  identifier = 'menu-articles'
  name = 'articles'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fas fa-articles'></i>"
  url = '/articles/'
  weight = -90
[[menu.main]]
  identifier = 'menu-api'
  name = 'api'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fas fa-alert'></i>"
  url = '/api'
  weight = -80
[[menu.main]]
  identifier = 'menu-search'
  name = 'search'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fas fa-search'></i>"
  url = '/search'
  weight = -70

[author]
  name="dev iron"
  homepage="https://ironpot.netlify.app"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"